### ISSUE TITLE
Left and right shift operators cause panic due to overflow.

### ISSUE THREAD

**Issue by a2aaron** [a2aaron/bytebot#15]
Bytebeat inputs such as `t -1 <<` or `t -1 >>` cause rust to panic with `thread 'main' panicked at 'attempt to shift left with overflow', src/lib.rs:113` or similar. This is due to the fact that `t << -1` is always illegal in Rust. To fix, we should probably make sure that the shift amount is always positive.

**Comment by porglezomp** [comment]
Specifically, shifting by an amount not in `0..64` is illegal for an `i64`
